### ISSUE TITLE
Option to put other authors (with ...) at the end of the entry

### ISSUE THREAD

**Issue by hliebert** [jspitz/biblatex-publist#14]
Would it be possible to create an option to put coauthors at the end of the entry, like in the example below?

Publication title, 2014, _Obscure Academic Journal_ 68, 116-136, (with S. Else and O. Person).

**Comment by jspitz** [comment]
Not in `biblatex-publist` itself, because this package does not define bibliography drivers (except for the new `review` type), and the order of elements in an entry is defined by the bibliography drivers.
But you'd simply need to use a different base style (see sec. 2.4 of the manual) and move author and editor to the end there. Alternatively, you can redefine the drivers in your document preamble, after biblatex was loaded.

The drivers used by default can be found in the file `standard.bbx` (shipped with biblatex). For article, a redefinition would look like this (untested):

```
\DeclareBibliographyDriver{article}{%
  \usebibmacro{bibindex}%
  \usebibmacro{begentry}%
%  \usebibmacro{author/translator+others}% <-- COMMENTED OUT HERE!
%  \setunit{\printdelim{nametitledelim}}\newblock <-- AND HERE!
  \usebibmacro{title}%
  \newunit
  \printlist{language}%
  \newunit\newblock
  \usebibmacro{byauthor}%
  \newunit\newblock
  \usebibmacro{bytranslator+others}%
  \newunit\newblock
  \printfield{version}%
  \newunit\newblock
  \usebibmacro{in:}%
  \usebibmacro{journal+issuetitle}%
  \newunit
  \usebibmacro{byeditor+others}%
  \newunit
  \usebibmacro{note+pages}%
  \newunit\newblock
  \iftoggle{bbx:isbn}
    {\printfield{issn}}
    {}%
  \newunit\newblock
  \usebibmacro{doi+eprint+url}%
  \newunit\newblock
  \usebibmacro{addendum+pubstate}%
  \setunit{\bibpagerefpunct}\newblock
  \usebibmacro{pageref}%
  \newunit\newblock
  \iftoggle{bbx:related}
    {\usebibmacro{related:init}%
     \usebibmacro{related}}
    {}%
 \usebibmacro{author/translator+others}% <-- AND MOVED HERE!
  \usebibmacro{finentry}}
```
