### ISSUE TITLE
Capitalized "and" after period (.) in name or initial

### ISSUE THREAD

**Issue by montdor** [jspitz/biblatex-publist#16]
I've come across a problem wherein if there is a period after someone's initial (be it middle initial or an initial for their first name) the "and" directly following it is capitalized.
E.g. if the article is written by John J. Doe and Jane D. Smith, the citation will read: Doe, John J. And Smith, Jane D.

**Comment by jspitz** [comment]
can you please upload an example file?

**Comment by jspitz** [comment]
It's a biblatex issue. Biblatex only supports to output all author names with initials (via `giveninits=true`), or none (default). If `giveninits=true` biblatex either expects the full name in the bibliography (John James Doe) or initial without dot (John J Doe). In both cases, all given names will be abbreviated (J. J. Doe)  and an abbreviation dot will be added (which will leave "and" lowercased).

If you want initials only for some entries (without `giveninits=true`), you need to use the macro `\adddot` rather than a literal dot: `John J\adddot Doe`. Note that you also need to use the macro in the `\plauthorname` macro then.

Closing this ticket, since it's not something we can tackle in biblatex-publist.

**Comment by montdor** [comment]
It doesn't look like that's the specific issue, as when i change everything to not use biblatex-publist, it exports as expected vis-a-vis the periods and the lowercase 'and' (except for the highlighted name and the sorting by month and year, of course, which is why this package is so awesome). I'll try and get a file uploaded that's deidentified if you think that would help at all.

**Comment by jspitz** [comment]
You might be right.

**Comment by jspitz** [comment]
Fixed in 1.12. All that was needed is `\isdot` after the respective name part.
