### ISSUE TITLE
Enhancement: URL title

### ISSUE THREAD

**Issue by abjer** [jspitz/biblatex-publist#22]
Hello there

Thanks for making publist, it is great and easy to work with! 

I was wondering whether you have thought about allowing users of the package to turn title of bibliography references (papers, books, etc.) into clickable links? The source of the URL for the link could be specified in the bibtex file. The implementation could perhaps build on the solution found in [this StackExchange thread](https://tex.stackexchange.com/questions/48400/biblatex-make-title-hyperlink-to-dois-url-or-isbn).

**Comment by jspitz** [comment]
Do you mean, as in the linked thread, links of titles via ISBN and ISSN (over worldcat or google books) as well, or only explicit links as specified via URL or DOI field?

**Comment by abjer** [comment]
I thought that explicit links via URL or from DOI would be easiest and would allow enough customization for my needs. I could see that the ISBN and ISSN provided links could be smart, but I guess that I currently would not use these.

**Comment by jspitz** [comment]
I have implemented something. Please try with https://github.com/jspitz/biblatex-publist/commit/1cc591ccba77fe67628856c04bff6d021493481c.

I have implemented these options (all false by default):

- `linktitleall` (consider DOI, URL, ISBN, and ISSN)
- `linktitledoi`
- `linktitleurl`
- `linktitleisbn`
- `linktitleissn`

Other than on the linked stackexchange thread, if have used a biber sourcemap, since this is more portable with other styles.

Please test and report back if this works for you.

**Comment by abjer** [comment]
Awesome, I will have a look very soon. Thanks!

**Comment by abjer** [comment]
It works very well for me. I didn't try ISBN or ISSN but I would assume they worked as well.

**Comment by jspitz** [comment]
Thanks for testing. I've just released v.1.17.
