### ISSUE TITLE
output of textcite

### ISSUE THREAD

**Issue by u-fischer** [jspitz/biblatex-publist#36]
I know citations are not really the purpose of the package, but I wonder nevertheless if the output of \textcite is actually intended:

~~~~
\documentclass{article}
\usepackage[style=publist]{biblatex}
\addbibresource{biblatex-examples.bib}
\begin{document}
\textcite{doody}
\printbibliography
\end{document}
~~~~

![image](https://user-images.githubusercontent.com/4047173/145689705-9118f821-83d8-4b05-9ae3-dd62dab12fa7.png)

**Comment by jspitz** [comment]
It's a collateral effect of the code that assures `extradate` labels are appended to all works within a year (notwithstanding the author group) in omit mode. There does not seem to be a straightforward other solution to achieve this. See discussion at #19.

The more complex code @moewew provided at https://github.com/jspitz/biblatex-publist/issues/19#issuecomment-447573168 works around this issue but it breaks with `pubstateextra=true` (and I don't know with what else).

I am not sure addressing this and risking other breakage is worth it since, as you said, this package is not meant for citing. I could change the definition of `\textcite` within `publist.cbx` to omit the `labelname` in the citation. But then this would still break if people use a different `citestyle`.

**Comment by jspitz** [comment]
Fixed as good as it gets at https://github.com/jspitz/biblatex-publist/commit/2376f03eba8c409c20dfbfc9847ef0c850240e32
